DialogChatBotsSystem/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DialogChatBotsSystem import settings
from WebMessageServices import routers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("WebDashboard.urls")),
    # Django Rest Framework
    path('api/', include(routers.router.urls)),
    path('api/', include("WebMessageServices.urls")),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('froala_editor/', include('froala_editor.urls')),
]
handler404 = 'WebDashboard.views.error'
handler500 = 'WebDashboard.views.error'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebDashboard/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    path('', views.empty, name='empty'),
    path('analytic', views.analytic, name='analytic'),
    path('input', views.inputDataTrain, name='input'),
    path('dictionary', views.dictionary, name='dictionary'),

    path('dictionary_api', views.dictionary_api, name='dictionary_api'),
    path('dictionary_api/load_file', views.dictionary_database_load_file, name='dictionary_load_file'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

WebDashboard/models.py
import froala_editor
from django.core.validators import RegexValidator
from django.db import models
from djongo import models as djongo

# Create your models here.
from froala_editor.fields import FroalaField


class StoreFile(models.Model):
    nameFileUpload = models.CharField(max_length=1000)
    urlPath = models.CharField(max_length=1000)  # url get file view browser
    sizeFile = models.FloatField()
    extension = models.CharField(max_length=8)
    dateTime = models.DateTimeField(auto_now_add=True)


class FeedBack(models.Model):
    rateMark = models.IntegerField(default=0)
    description = models.TextField()
    dateTime = models.DateTimeField(auto_now=True)

    class Meta:  # NTT embedded ConversationLog
        abstract = True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class Messages(models.Model):
    question = models.TextField()
    answer = models.TextField()

    class Meta:
        abstract = True

    def __str__(self):
        return 'question :: {question} -> answer :: {answer}'.format(question=self.question, answer=self.answer)


class ConversationLog(models.Model):
    # person = models.ManyToOneRel('person', to='Person', field_name='_id')
    feedback = djongo.EmbeddedModelField(
        model_container=FeedBack,
    )
    dateTime = models.DateTimeField(auto_now_add=True)
    history_message = djongo.ArrayModelField(
        model_container=Messages
    )

    def __str__(self):
        return str(self.history_message)

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question', None)
        answer = kwargs.pop('answer', None)
        super().__init__(*args, **kwargs)
        if self.feedback is None:
            self.feedback = FeedBack(None)
        if not question is None and not answer is None:
            self.history_message = [Messages(question=question, answer=answer)]
        elif self.history_message is None:
            self.history_message = []

    def add_history_mesage(self, question, answer):
        if not question is None and not answer is None:
            self.history_message.append(Messages(question=question, answer=answer))
            # self.save()


class NotificationDevice(models.Model):
    idClientDevice = models.CharField(max_length=200)
    optionNotify = models.BooleanField(default=True)

    def __str__(self):
        return str.format("Device ID :: ", self.idClientDevice)


class Person(models.Model):
    name = models.CharField(max_length=2000)
    province = models.TextField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    numberPhone = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    email = models.EmailField()
    devices = djongo.ForeignObject(
        to=NotificationDevice,
        from_fields=["person_devices"],
        to_fields=["id"],
        on_delete=djongo.CASCADE)

    def __str__(self):
        return self.name


class SenderGroup(models.Model):  # as group sender
    name = models.CharField(max_length=200)
    listIdDevices = djongo.ArrayModelField(
        model_container=NotificationDevice
    )
    # TODO NTT continue handle....


class NotificationContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    dateTime = models.DateTimeField(auto_now_add=True)
    senderGroup = models.ManyToManyField(SenderGroup)

    def __str__(self):
        return self.title


class Menu(models.Model):
    title = models.CharField(max_length=200)
    keyName = models.CharField(max_length=200)
    description = models.TextField()

    # TODO NTT handle continue....

    def __str__(self):
        return self.keyName


class ChatMessage(models.Model):
    questionMessage = models.TextField()
    answerMessage = FroalaField(plugins=froala_editor.PLUGINS,
                                options={
                                    'toolbarInline': False,
                                })
    questionProcessed = models.TextField()
    answerProcessed = models.TextField()
    timeDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.questionMessage


class DictionaryWord(models.Model):
    word = models.TextField()
    value = models.IntegerField(db_index=True)
    mapping = djongo.ListField(models.TextField())
    updateTime = models.DateTimeField(auto_now=True)

    def mapping_insert(self, word):
        self.mapping.insert(len(self.mapping), word)
        self.save()

    def mapping_remove(self, word):
        self.mapping.remove(word)
        self.save()

    def __str__(self):
        return '\nword ::: {0} value: {1} mapping: [{2}]'.format(self.word, self.value, self.mapping)

templates/content_editor/dictionary-content.html
{% extends "layout_dashboard/container-app.html" %} {% block contentContainer %}
    <div class="page-content-wrapper custom-scrollbar">
        <!-- HEADER -->
        {% include "layout_dashboard/components/header-content.html" with titleHeaderContent=title %}

        <!-- CONTENT -->
        <div class="page-content">

            <ul class="nav nav-tabs row" id="myTab" role="tablist">

                <li class="nav-item">
                    <a class="nav-link btn active" id="home-tab" data-toggle="tab" href="#home-tab-pane" role="tab"
                       aria-controls="home-tab-pane"
                       aria-expanded="true">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link btn" id="budget-summary-tab" data-toggle="tab" href="#budget-summary-tab-pane"
                       role="tab" aria-controls="budget-summary-tab-pane">Budget Summary</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link btn" id="team-members-tab" data-toggle="tab" href="#team-members-tab-pane"
                       role="tab" aria-controls="team-members-tab-pane">Team Members</a>
                </li>
            </ul>

            <div class="tab-content"> {# contains content of tab #}
                <div class="tab-pane fade show active p-3" id="home-tab-pane" role="tabpanel"
                     aria-labelledby="home-tab">
                    <!-- WIDGET GROUP -->
                    <div class="widget-group no-gutters p-10">
                      {% include 'content_editor/map-key-dictionary.html' %}
                    </div>
                    <!-- / WIDGET GROUP -->
                </div>
                <div class="tab-pane fade p-3" id="budget-summary-tab-pane" role="tabpanel"
                     aria-labelledby="budget-summary-tab">
                    {# TODO content here!!! #} You write code here!!! TAG BUDGET SUMMARY
                </div>
                <div class="tab-pane fade p-6" id="team-members-tab-pane" role="tabpanel"
                     aria-labelledby="team-members-tab">
                    <!-- WIDGET GROUP -->
                    <div class="widget-group row no-gutters">
                        <!-- WIDGET 1 -->
                        <div class="col-12">
                            <div class="card">
                                {# TODO content here!!! #} You write code here!!! TAG TEAM MEMBER
                            </div>
                        </div>
                        <!-- WIDGET 1 -->
                    </div>
                </div>
            </div>

        </div>
        <!-- / CONTENT -->
    </div>
{% endblock %}

templates/content_editor/input-data-train-content.html
{% extends "layout_dashboard/container-app.html" %}
{% block contentContainer %}
    <div class="page-content-wrapper custom-scrollbar">
        <!-- HEADER -->
        {% include "layout_dashboard/components/header-content.html" with titleHeaderContent="Input data training" %}
        <!-- CONTENT -->
        <div class="page-content">
            <div class="p-6 content container custom-scrollbar">
                <form method="POST" action={% url 'input' %}>
                    {% csrf_token %}

                    {% if inputDataTrainForm %} {% comment %} Test UI {% endcomment %}
                        <div class="form-group">
                            <label for="id_questionMessage">Question data</label>
                            {{ inputDataTrainForm.questionMessage }}
                        </div>

                        <div class="form-group">
                            <label>Answer data</label>
                            {{ inputDataTrainForm.answerMessage }}
                            </small>
                        </div>
                        <div class="button-form fc-button-group col-lg-4 col-sm-12"
                             style="float: right; text-align: center">
                            <button type="submit" class="btn btn-primary btn-default col-lg-5 col-sm-6"
                                    style="float: left">Submit
                            </button>
                            <button type="reset" class="btn btn-danger btn-default col-lg-5 col-sm-6"
                                    style="float: right">Reset
                            </button>
                        </div>
                    {% endif %}
                </form>
            </div>
            {% include "layout_dashboard/editor-loader.html" %}

        </div>
        <!-- / CONTENT -->
    </div>
{% endblock %}

templates/content_editor/map-key-dictionary.html
{#  TWO SEARCH COMPONENT  #}
<div class="row row-sm-6">
    <div class="col-12 col-lg-6 p-3">
        <div class="search-wrapper md-elevation-1 row no-gutters align-items-center w-100 p-2">
            <i class="icon-magnify s-4"></i>
            <input class="col pl-2" type="text" placeholder="Search word to dictionary..." required
                   name="searchWordDictionaryPrimary"
                   onkeyup="searchWordDictionaryPrimary('{% url 'dictionary_api' %}','{{ csrf_token }}',event)">
        </div>
        <div class="custom-scrollbar ps ps--theme_default">
            <div class="custom-scrollbar ps ps--theme_default m-2" style="max-height: 25vh;"
                 id="listSearchPrimary">
                {% comment %} NTT DOM LIST SEARCH RESUAL WITH listSearchMapping {% endcomment %}
                {% comment %}<li name="itemSearch" id="itemSearch"
                        class="ripple flex-wrap flex-sm-nowrap row p-2 no-gutters align-items-center"
                        value_word="3" onclick="setValueItemSelect($(this))">SPKT
                    </li>{% endcomment %}
                </div>
            </div>
    </div>

    <div class="col-12 col-lg-6 p-3">
        <div class="search-wrapper md-elevation-1 row no-gutters align-items-center w-100 p-2">
            <i class="icon-magnify s-4"></i>
            <input class="col pl-2" type="text" placeholder="Search word to dictionary mapping..." required
                   name="searchWordDictionaryMapping"
                   onkeyup="searchWordDictionaryMapping('{% url 'dictionary_api' %}','{{ csrf_token }}',event)">
                </div>
        <div class="custom-scrollbar ps ps--theme_default">
            <div class="custom-scrollbar ps ps--theme_default m-2" style="max-height: 25vh;"
                 id="listSearchMapping">
                {% comment %} NTT DOM LIST SEARCH RESUAL WITH listSearchMapping {% endcomment %}
            </div>
        </div>
    </div>
</div>
{#  \TWO SEARCH COMPONENT  #}

<div class="row" style="display:flex; justify-content:space-between; margin: 10px">
    <div class="chooseItem">
        <p class="text-left">Word primary current: </p>
    </div>
    <div class="chooseItem">
        <strong id="textChoose"></strong>
    </div>
</div>

<div id="listPreViewMapping" class="card">
    {% comment %}<div class="card" word_key="SPKT">
            <div class="card-header" role="tab" id="headingSPKT" aria-expanded="true" aria-controls="collapseSPKT">
                <a data-toggle="collapse" href="#collapseSPKT" class="collapsed"
                   style="display: flex; justify-content: space-between; text-decoration: none;">
                    <strong word_key="collapseSPKT" word_value="3" style="display: flex; align-items: center;">
                        SPKT
                    </strong>
                    <div class="md-elevation-1 row no-gutters align-items-center w-50 p-2">
                        <input class="col pl-2 dispose" type="text" placeholder="Add new word to dictionary..." required
                               id="idMapNewWordForInput" onkeyup="handleEnterKey(event,addNewWordToDictionary)"
                               style="background: transparent">
                        <i class="icon-tooltip-outline-plus" onclick="addNewWordToDictionary()"></i>
                    </div>
                    <button type="button" class="btn btn-secondary btn-fab btn-sm"
                            onclick="submitUpdataWordValue($(this))">
                        <i class="icon-send"></i>
                    </button>
                </a>
            </div>
            <div id="collapseSPKT" class="collapse show" role="tabpanel" aria-labelledby="headingSPKT"
                 data-parent="#listPreViewMapping">
                <div class="card-block">
                    <!--  NTT TABLE    -->
                    <table id="sample-data-table" class="table">
                        <thead>
                        <tr>
                            <th class="secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Word key</span>
                                </div>
                            </th>
                            <th class="secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Worrd value</span>
                                </div>
                            </th>
                            <th class="secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Status</span>
                                </div>
                            </th>
                            <th class="secondary-text">
                                <div class="table-header">
                                    <span class="column-title">Actions</span>
                                </div>
                            </th>
                        </tr>
                        </thead>
                        <!-- ELEMENT ITEM LIST VIEW -->
                        <tbody>
                        <tr>
                            <td>Brian Franklin</td>
                            <td>Project Manager</td>
                            <td>
                                <i class="quantity-indicator icon-circle s-3 text-success mr-1"></i>Mapped
                            </td>
                            <td>
                                <button class="badge badge-pill badge-danger p-2 pl-4 pr-4">Detack</button>
                            </td>
                        </tr>
                        <tr>
                            <td>Brian Franklin</td>
                            <td>Project Manager</td>
                            <td>
                                <i class="quantity-indicator icon-circle s-3 text-warning mr-1"></i>To Mapping
                            </td>
                            <td>
                                <button class="badge badge-pill badge-info p-2 pl-4 pr-4">Cancel</button>
                            </td>
                        </tr>
                        <tr>
                            <td>Franklin</td>
                            <td>Broject Manager</td>
                            <td>
                                <i class="quantity-indicator icon-circle s-3 text-info mr-1"></i>Add New
                            </td>
                            <td>
                                <button class="badge badge-pill badge-warning p-2 pl-4 pr-4">Remove</button>
                            </td>
                        </tr>
                        </tbody>
                        <!--    \ELEMENT ITEM LIST VIEW -->
                    </table>

                    <script type="text/javascript">
                        $('#sample-data-table').DataTable({
                            responsive: true,
                            dom: 'rt<"dataTables_footer"ip>',
                        });
                    </script>
                    <!-- \NTT TABLE -->
                </div>
            </div>
        </div>{% endcomment %}
</div>

<script type="text/javascript" src="../../assets/js/apps/dictionary/mapping_dictionary.js"></script>